### ISSUE TITLE
data is empty?

### ISSUE THREAD

**Issue by liamxg** [CERI-KRISP/SARS_CoV_2_VOC_dissemination#1]
<img width="898" alt="image" src="https://user-images.githubusercontent.com/46078579/204212772-25a5f971-018f-4999-b515-47dfbd4a6e8b.png">

**Comment by liamxg** [comment]
@HouriiyahT @jsan4christ

**Comment by jsan4christ** [comment]
Thanks @liamxg for flagging that. We have resolved the issue and all files should now be available. There are a few data files that we do not yet have permission from the original authors to share (mobility data files). In case you cannot find these while running the scripts, that is the reason why. 

We will try to obtain permission for these soonest and then share here.

**Comment by liamxg** [comment]
@jsan4christ thanks. I am doing the similar project, hope you can help me.

**Comment by liamxg** [comment]
@jsan4christ I can not wait for other data to share.

**Comment by liamxg** [comment]
where can I find the meta data?

**Comment by HouriiyahT** [comment]
The sequence metadata can be downloaded from GISAID

**Comment by liamxg** [comment]
@HouriiyahT thanks for your reply, I got it, and this file is too big,  you must use a super cp, right?
btw, where can i find all_both, thanks.
![Uploading image.png…]()

**Comment by liamxg** [comment]
@jsan4christ
